type User @aws_cognito_user_pools @aws_iam {
  email: String!
  firstName: String
  lastName: String
  organization: String
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owner: String
}

type Paper @aws_cognito_user_pools @aws_iam {
  title: String!
  authors: String
  abstract: String
  status: String
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owner: String
}

input AmplifyAIConversationTurnErrorInput {
  errorType: String!
  message: String!
}

input ModelStringInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  size: ModelSizeInput
}

input ModelIntInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelFloatInput {
  ne: Float
  eq: Float
  le: Float
  lt: Float
  ge: Float
  gt: Float
  between: [Float]
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelBooleanInput {
  ne: Boolean
  eq: Boolean
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelIDInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  size: ModelSizeInput
}

input ModelSubscriptionStringInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
  in: [String]
  notIn: [String]
}

input ModelSubscriptionIntInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
  in: [Int]
  notIn: [Int]
}

input ModelSubscriptionFloatInput {
  ne: Float
  eq: Float
  le: Float
  lt: Float
  ge: Float
  gt: Float
  between: [Float]
  in: [Float]
  notIn: [Float]
}

input ModelSubscriptionBooleanInput {
  ne: Boolean
  eq: Boolean
}

input ModelSubscriptionIDInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
  in: [ID]
  notIn: [ID]
}

enum ModelAttributeTypes {
  binary
  binarySet
  bool
  list
  map
  number
  numberSet
  string
  stringSet
  _null
}

input ModelSizeInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
}

enum ModelSortDirection {
  ASC
  DESC
}

type ModelUserConnection @aws_cognito_user_pools @aws_iam {
  items: [User]!
  nextToken: String
}

input ModelUserFilterInput {
  email: ModelStringInput
  firstName: ModelStringInput
  lastName: ModelStringInput
  organization: ModelStringInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelUserFilterInput]
  or: [ModelUserFilterInput]
  not: ModelUserFilterInput
  owner: ModelStringInput
}

type Query {
  getUser(id: ID!): User @aws_cognito_user_pools @aws_iam
  listUsers(filter: ModelUserFilterInput, limit: Int, nextToken: String): ModelUserConnection @aws_cognito_user_pools @aws_iam
  getPaper(id: ID!): Paper @aws_cognito_user_pools @aws_iam
  listPapers(filter: ModelPaperFilterInput, limit: Int, nextToken: String): ModelPaperConnection @aws_cognito_user_pools @aws_iam
}

input ModelUserConditionInput {
  email: ModelStringInput
  firstName: ModelStringInput
  lastName: ModelStringInput
  organization: ModelStringInput
  and: [ModelUserConditionInput]
  or: [ModelUserConditionInput]
  not: ModelUserConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  owner: ModelStringInput
}

input CreateUserInput {
  email: String!
  firstName: String
  lastName: String
  organization: String
  id: ID
}

input UpdateUserInput {
  email: String
  firstName: String
  lastName: String
  organization: String
  id: ID!
}

input DeleteUserInput {
  id: ID!
}

type Mutation {
  createUser(input: CreateUserInput!, condition: ModelUserConditionInput): User @aws_cognito_user_pools @aws_iam
  updateUser(input: UpdateUserInput!, condition: ModelUserConditionInput): User @aws_cognito_user_pools @aws_iam
  deleteUser(input: DeleteUserInput!, condition: ModelUserConditionInput): User @aws_cognito_user_pools @aws_iam
  createPaper(input: CreatePaperInput!, condition: ModelPaperConditionInput): Paper @aws_cognito_user_pools @aws_iam
  updatePaper(input: UpdatePaperInput!, condition: ModelPaperConditionInput): Paper @aws_cognito_user_pools @aws_iam
  deletePaper(input: DeletePaperInput!, condition: ModelPaperConditionInput): Paper @aws_cognito_user_pools @aws_iam
}

input ModelSubscriptionUserFilterInput {
  email: ModelSubscriptionStringInput
  firstName: ModelSubscriptionStringInput
  lastName: ModelSubscriptionStringInput
  organization: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionUserFilterInput]
  or: [ModelSubscriptionUserFilterInput]
  owner: ModelStringInput
}

type Subscription {
  onCreateUser(filter: ModelSubscriptionUserFilterInput, owner: String): User @aws_subscribe(mutations: ["createUser"]) @aws_cognito_user_pools @aws_iam
  onUpdateUser(filter: ModelSubscriptionUserFilterInput, owner: String): User @aws_subscribe(mutations: ["updateUser"]) @aws_cognito_user_pools @aws_iam
  onDeleteUser(filter: ModelSubscriptionUserFilterInput, owner: String): User @aws_subscribe(mutations: ["deleteUser"]) @aws_cognito_user_pools @aws_iam
  onCreatePaper(filter: ModelSubscriptionPaperFilterInput, owner: String): Paper @aws_subscribe(mutations: ["createPaper"]) @aws_cognito_user_pools @aws_iam
  onUpdatePaper(filter: ModelSubscriptionPaperFilterInput, owner: String): Paper @aws_subscribe(mutations: ["updatePaper"]) @aws_cognito_user_pools @aws_iam
  onDeletePaper(filter: ModelSubscriptionPaperFilterInput, owner: String): Paper @aws_subscribe(mutations: ["deletePaper"]) @aws_cognito_user_pools @aws_iam
}

type ModelPaperConnection @aws_cognito_user_pools @aws_iam {
  items: [Paper]!
  nextToken: String
}

input ModelPaperFilterInput {
  title: ModelStringInput
  authors: ModelStringInput
  abstract: ModelStringInput
  status: ModelStringInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelPaperFilterInput]
  or: [ModelPaperFilterInput]
  not: ModelPaperFilterInput
  owner: ModelStringInput
}

input ModelPaperConditionInput {
  title: ModelStringInput
  authors: ModelStringInput
  abstract: ModelStringInput
  status: ModelStringInput
  and: [ModelPaperConditionInput]
  or: [ModelPaperConditionInput]
  not: ModelPaperConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  owner: ModelStringInput
}

input CreatePaperInput {
  title: String!
  authors: String
  abstract: String
  status: String
  id: ID
}

input UpdatePaperInput {
  title: String
  authors: String
  abstract: String
  status: String
  id: ID!
}

input DeletePaperInput {
  id: ID!
}

input ModelSubscriptionPaperFilterInput {
  title: ModelSubscriptionStringInput
  authors: ModelSubscriptionStringInput
  abstract: ModelSubscriptionStringInput
  status: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionPaperFilterInput]
  or: [ModelSubscriptionPaperFilterInput]
  owner: ModelStringInput
}
